name = "SARA_Crystal"
uuid = "dda4b776-b026-4f05-b4c4-a8a6ffbc58d4"
authors = ["Ming-Chiang Chang <mc2663@cornell.edu>"]
version = "0.1.0"

[deps]
BackgroundSubtraction = "9977cdcb-3521-4027-9f3f-3caff6505f42"
CovarianceFunctions = "b3329135-7958-41d4-bb02-e084c5a526bf"
CrystalShift = "fb120844-f04e-4a6b-a6eb-278194263097"
CrystalTree = "9c8cff83-2ad6-4961-8214-2a9086396538"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussianDistributions = "bca5bafc-9f2e-496c-8c30-2a4e9dcd8e59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
